//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromotionEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionFormula
    {
        public int PromotionFormulaId { get; set; }
        public int PromotionId { get; set; }
        public int ItemQty { get; set; }
        public string ItemNames { get; set; }
        public int PromotionValue { get; set; }
        public string FormulaDescription { get; set; }
    
        public virtual Promotion Promotion { get; set; }
    }
}
